version: '3.8'

services:
  # ========= database =======
  database:
    image: postgres
    container_name: grothDB_container
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    command: postgres
  # ========= end database =======

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always
    ports:
      - '5050:80'

  redis:
    image: redis:alpine3.14
    container_name: redis-container
    ports:
      - '6379-6379'
  # ========= end database =======
